// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sessions} from '../models';

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<sessions.Session>;

export function List():Promise<Array<sessions.SessionMeta>>;

export function Save(arg1:string,arg2:string,arg3:string):Promise<void>;
