// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['sessions']['Sessions']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['sessions']['Sessions']['Get'](arg1);
}

export function List() {
  return window['go']['sessions']['Sessions']['List']();
}

export function Save(arg1, arg2, arg3) {
  return window['go']['sessions']['Sessions']['Save'](arg1, arg2, arg3);
}
