// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connectors} from '../models';

export function CheckAll():Promise<Array<connectors.Status>>;

export function CheckAuth(arg1:string):Promise<connectors.Status>;

export function Connect(arg1:string):Promise<void>;

export function Install(arg1:string):Promise<void>;
