// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAll() {
  return window['go']['connectors']['Connectors']['CheckAll']();
}

export function CheckAuth(arg1) {
  return window['go']['connectors']['Connectors']['CheckAuth'](arg1);
}

export function Connect(arg1) {
  return window['go']['connectors']['Connectors']['Connect'](arg1);
}

export function Install(arg1) {
  return window['go']['connectors']['Connectors']['Install'](arg1);
}
