// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Catalog() {
  return window['go']['skills']['Skills']['Catalog']();
}

export function List() {
  return window['go']['skills']['Skills']['List']();
}

export function Read(arg1) {
  return window['go']['skills']['Skills']['Read'](arg1);
}
