// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skills} from '../models';

export function Catalog():Promise<string>;

export function List():Promise<Array<skills.Skill>>;

export function Read(arg1:string):Promise<string>;
