// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateOverview(arg1) {
  return window['go']['overview']['Overview']['GenerateOverview'](arg1);
}

export function Get() {
  return window['go']['overview']['Overview']['Get']();
}
