// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {overview} from '../models';

export function GenerateOverview(arg1:string):Promise<void>;

export function Get():Promise<overview.Data>;
