// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ask} from '../models';

export function Answer(arg1:string,arg2:string):Promise<void>;

export function Pending():Promise<Array<ask.Question>>;
