// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Answer(arg1, arg2) {
  return window['go']['ask']['Ask']['Answer'](arg1, arg2);
}

export function Pending() {
  return window['go']['ask']['Ask']['Pending']();
}
