// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowServer(arg1) {
  return window['go']['settings']['Settings']['AllowServer'](arg1);
}

export function DeleteAPIKey() {
  return window['go']['settings']['Settings']['DeleteAPIKey']();
}

export function Get() {
  return window['go']['settings']['Settings']['Get']();
}

export function GetAPIKey() {
  return window['go']['settings']['Settings']['GetAPIKey']();
}

export function GetAllowedServers() {
  return window['go']['settings']['Settings']['GetAllowedServers']();
}

export function HasAPIKey() {
  return window['go']['settings']['Settings']['HasAPIKey']();
}

export function RemoveServer(arg1) {
  return window['go']['settings']['Settings']['RemoveServer'](arg1);
}

export function Set(arg1) {
  return window['go']['settings']['Settings']['Set'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['settings']['Settings']['SetAPIKey'](arg1);
}
