// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function AllowServer(arg1:settings.Server):Promise<void>;

export function DeleteAPIKey():Promise<void>;

export function Get():Promise<settings.Config>;

export function GetAPIKey():Promise<string>;

export function GetAllowedServers():Promise<Array<settings.Server>>;

export function HasAPIKey():Promise<boolean>;

export function RemoveServer(arg1:string):Promise<void>;

export function Set(arg1:settings.Config):Promise<void>;

export function SetAPIKey(arg1:string):Promise<void>;
