// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeCwd(arg1) {
  return window['go']['main']['App']['ChangeCwd'](arg1);
}

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function ChooseKeyFile() {
  return window['go']['main']['App']['ChooseKeyFile']();
}

export function CloneRepo(arg1) {
  return window['go']['main']['App']['CloneRepo'](arg1);
}

export function ShellPath(arg1) {
  return window['go']['main']['App']['ShellPath'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WorkspacesDir() {
  return window['go']['main']['App']['WorkspacesDir']();
}
