// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeCwd(arg1) {
  return window['go']['main']['App']['ChangeCwd'](arg1);
}

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function ChooseKeyFile() {
  return window['go']['main']['App']['ChooseKeyFile']();
}

export function CloneRepo(arg1) {
  return window['go']['main']['App']['CloneRepo'](arg1);
}

export function LogError(arg1, arg2) {
  return window['go']['main']['App']['LogError'](arg1, arg2);
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function ShellPath(arg1) {
  return window['go']['main']['App']['ShellPath'](arg1);
}

export function ShowErrorLog() {
  return window['go']['main']['App']['ShowErrorLog']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WorkspacesDir() {
  return window['go']['main']['App']['WorkspacesDir']();
}
