// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeCwd(arg1:string):Promise<void>;

export function ChooseDirectory():Promise<string>;

export function ChooseKeyFile():Promise<string>;

export function CloneRepo(arg1:string):Promise<string>;

export function LogError(arg1:string,arg2:string):Promise<void>;

export function Restart():Promise<void>;

export function ShellPath(arg1:string):Promise<string>;

export function ShowErrorLog():Promise<void>;

export function Update():Promise<void>;

export function Version():Promise<main.VersionInfo>;

export function WorkspacesDir():Promise<string>;
