// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tools} from '../models';

export function Check(arg1:string):Promise<tools.AgentStatus>;

export function Models(arg1:string):Promise<Array<tools.Model>>;

export function ResolveSecret(arg1:string,arg2:string):Promise<void>;

export function Run(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
