// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check(arg1) {
  return window['go']['tools']['Harness']['Check'](arg1);
}

export function Models(arg1) {
  return window['go']['tools']['Harness']['Models'](arg1);
}

export function ResolveSecret(arg1, arg2) {
  return window['go']['tools']['Harness']['ResolveSecret'](arg1, arg2);
}

export function Run(arg1, arg2, arg3, arg4) {
  return window['go']['tools']['Harness']['Run'](arg1, arg2, arg3, arg4);
}
