// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['tools']['SSH']['Connect'](arg1, arg2, arg3, arg4);
}

export function Disconnect(arg1) {
  return window['go']['tools']['SSH']['Disconnect'](arg1);
}

export function RunRemote(arg1, arg2, arg3) {
  return window['go']['tools']['SSH']['RunRemote'](arg1, arg2, arg3);
}
