// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function Disconnect(arg1:string):Promise<string>;

export function RunRemote(arg1:string,arg2:string,arg3:string):Promise<string>;
