// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveNextTurn() {
  return window['go']['tools']['Tool']['ApproveNextTurn']();
}

export function AskQuestion(arg1, arg2, arg3) {
  return window['go']['tools']['Tool']['AskQuestion'](arg1, arg2, arg3);
}

export function Cancel(arg1) {
  return window['go']['tools']['Tool']['Cancel'](arg1);
}

export function ClearRunSecrets() {
  return window['go']['tools']['Tool']['ClearRunSecrets']();
}

export function GetCwd() {
  return window['go']['tools']['Tool']['GetCwd']();
}

export function GetSystemInfo() {
  return window['go']['tools']['Tool']['GetSystemInfo']();
}

export function SetRunSecret(arg1, arg2) {
  return window['go']['tools']['Tool']['SetRunSecret'](arg1, arg2);
}

export function ShellAccess(arg1, arg2) {
  return window['go']['tools']['Tool']['ShellAccess'](arg1, arg2);
}

export function ShellStatus() {
  return window['go']['tools']['Tool']['ShellStatus']();
}
