// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shell} from '../models';

export function ApproveNextTurn():Promise<void>;

export function AskQuestion(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Cancel(arg1:string):Promise<void>;

export function ClearRunSecrets():Promise<void>;

export function GetCwd():Promise<string>;

export function GetSystemInfo():Promise<string>;

export function SetRunSecret(arg1:string,arg2:string):Promise<void>;

export function ShellAccess(arg1:string,arg2:string):Promise<string>;

export function ShellStatus():Promise<shell.Status>;
